# Generated by Django 2.0.7 on 2020-04-07 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='name',
        ),
    ]
