# Generated by Django 2.0.7 on 2020-04-07 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_usermessage_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='is_member',
            field=models.BooleanField(default=False, verbose_name='会员'),
        ),
        migrations.AddField(
            model_name='usermessage',
            name='open_date',
            field=models.DateField(blank=True, null=True, verbose_name='开通时间'),
        ),
    ]
