# Generated by Django 2.0.7 on 2020-04-13 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_usersign'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_no', models.CharField(max_length=20, verbose_name='流水号')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='商品价格')),
                ('mem_time', models.DateTimeField(verbose_name='开通时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '会员支付表',
                'verbose_name_plural': '会员支付表',
            },
        ),
        migrations.AlterField(
            model_name='usersign',
            name='signdate',
            field=models.DateField(),
        ),
    ]
