# Generated by Django 2.0.7 on 2020-04-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200413_1333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermember',
            options={'verbose_name': '会员开通流水表', 'verbose_name_plural': '会员开通流水表'},
        ),
        migrations.RemoveField(
            model_name='usermember',
            name='id',
        ),
        migrations.AddField(
            model_name='usermember',
            name='order_no',
            field=models.BigAutoField(default='610000000001', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usermember',
            name='mem_time',
            field=models.DateTimeField(verbose_name='创建时间'),
        ),
    ]
