# Generated by Django 2.0.7 on 2020-04-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200414_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermember',
            name='pay_status',
            field=models.CharField(choices=[('0', '待支付'), ('1', '已支付')], default='0', max_length=6, verbose_name='支付状态'),
        ),
    ]
