# Generated by Django 2.0.7 on 2020-04-14 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usermember_pay_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='order_no',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
