# Generated by Django 2.0.7 on 2020-04-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200414_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermember',
            name='sale_no',
            field=models.CharField(max_length=20, verbose_name='支付宝订单号'),
        ),
        migrations.AlterField(
            model_name='usermessage',
            name='type',
            field=models.CharField(choices=[('stu', '学员'), ('tea', '教练')], max_length=10, verbose_name='用户类型'),
        ),
        migrations.AlterField(
            model_name='usersign',
            name='signdate',
            field=models.DateField(verbose_name='签到日期'),
        ),
    ]
