# Generated by Django 2.0.7 on 2020-04-14 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': '教练', 'verbose_name_plural': '教练'},
        ),
    ]
